"""initial schema: 10 tables

Revision ID: aaa936fed1ab
Revises: 
Create Date: 2026-10-03 23:12:54.601915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aaa936fed1ab'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('timezone', sa.String(length=64), server_default='Asia/Kolkata', nullable=False),
    sa.Column('goals', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('health_conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('daily_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('summary_date', sa.Date(), nullable=False),
    sa.Column('total_calories', sa.Float(), nullable=True),
    sa.Column('total_protein_g', sa.Float(), nullable=True),
    sa.Column('total_carbs_g', sa.Float(), nullable=True),
    sa.Column('total_fat_g', sa.Float(), nullable=True),
    sa.Column('total_fiber_g', sa.Float(), nullable=True),
    sa.Column('calories_burned', sa.Float(), nullable=True),
    sa.Column('meals_logged', sa.Integer(), nullable=True),
    sa.Column('exercises_logged', sa.Integer(), nullable=True),
    sa.Column('totals', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'summary_date', name='uq_daily_summaries_user_date')
    )
    op.create_index(op.f('ix_daily_summaries_user_id'), 'daily_summaries', ['user_id'], unique=False)
    op.create_table('llm_monitoring_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('operation', sa.String(length=80), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('langfuse_trace_id', sa.String(length=100), nullable=True),
    sa.Column('prompt_version', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_monitoring_logs_langfuse_trace_id'), 'llm_monitoring_logs', ['langfuse_trace_id'], unique=False)
    op.create_index(op.f('ix_llm_monitoring_logs_user_id'), 'llm_monitoring_logs', ['user_id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('report_type', sa.Enum('weekly', 'monthly', name='report_type'), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('detected_patterns', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_insights', sa.Text(), nullable=True),
    sa.Column('chart_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('langfuse_trace_id', sa.String(length=100), nullable=True),
    sa.Column('prompt_version', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'report_type', 'period_start', name='uq_reports_user_type_start')
    )
    op.create_index(op.f('ix_reports_langfuse_trace_id'), 'reports', ['langfuse_trace_id'], unique=False)
    op.create_index(op.f('ix_reports_user_id'), 'reports', ['user_id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('memory_summarized', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'session_date', name='uq_sessions_user_date')
    )
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('user_memory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('food_preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('usual_meals', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('eating_patterns', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('typical_calories', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('health_notes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('misc', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('conversation_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('user', 'assistant', 'tool', 'system', name='message_role'), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('tool_name', sa.String(length=100), nullable=True),
    sa.Column('tool_calls', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('langfuse_trace_id', sa.String(length=100), nullable=True),
    sa.Column('prompt_version', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_messages_langfuse_trace_id'), 'conversation_messages', ['langfuse_trace_id'], unique=False)
    op.create_index(op.f('ix_conversation_messages_session_id'), 'conversation_messages', ['session_id'], unique=False)
    op.create_index(op.f('ix_conversation_messages_user_id'), 'conversation_messages', ['user_id'], unique=False)
    op.create_table('exercise_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('raw_message', sa.Text(), nullable=False),
    sa.Column('exercise_type', sa.String(length=120), nullable=True),
    sa.Column('duration_min', sa.Float(), nullable=True),
    sa.Column('calories_burned', sa.Float(), nullable=True),
    sa.Column('confidence_tier', sa.Enum('high', 'medium', 'low', name='confidence_tier'), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('logged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('langfuse_trace_id', sa.String(length=100), nullable=True),
    sa.Column('prompt_version', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercise_logs_langfuse_trace_id'), 'exercise_logs', ['langfuse_trace_id'], unique=False)
    op.create_index(op.f('ix_exercise_logs_log_date'), 'exercise_logs', ['log_date'], unique=False)
    op.create_index(op.f('ix_exercise_logs_session_id'), 'exercise_logs', ['session_id'], unique=False)
    op.create_index(op.f('ix_exercise_logs_user_id'), 'exercise_logs', ['user_id'], unique=False)
    op.create_table('food_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('raw_message', sa.Text(), nullable=False),
    sa.Column('meal_type', sa.Enum('breakfast', 'lunch', 'dinner', 'snack', 'other', name='meal_type'), nullable=True),
    sa.Column('confidence_tier', sa.Enum('high', 'medium', 'low', name='confidence_tier'), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('logged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('langfuse_trace_id', sa.String(length=100), nullable=True),
    sa.Column('prompt_version', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_food_logs_langfuse_trace_id'), 'food_logs', ['langfuse_trace_id'], unique=False)
    op.create_index(op.f('ix_food_logs_log_date'), 'food_logs', ['log_date'], unique=False)
    op.create_index(op.f('ix_food_logs_session_id'), 'food_logs', ['session_id'], unique=False)
    op.create_index(op.f('ix_food_logs_user_id'), 'food_logs', ['user_id'], unique=False)
    op.create_table('food_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('food_log_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('calories', sa.Float(), nullable=True),
    sa.Column('protein_g', sa.Float(), nullable=True),
    sa.Column('carbs_g', sa.Float(), nullable=True),
    sa.Column('fat_g', sa.Float(), nullable=True),
    sa.Column('fiber_g', sa.Float(), nullable=True),
    sa.Column('micronutrients', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['food_log_id'], ['food_logs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_food_items_food_log_id'), 'food_items', ['food_log_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_food_items_food_log_id'), table_name='food_items')
    op.drop_table('food_items')
    op.drop_index(op.f('ix_food_logs_user_id'), table_name='food_logs')
    op.drop_index(op.f('ix_food_logs_session_id'), table_name='food_logs')
    op.drop_index(op.f('ix_food_logs_log_date'), table_name='food_logs')
    op.drop_index(op.f('ix_food_logs_langfuse_trace_id'), table_name='food_logs')
    op.drop_table('food_logs')
    op.drop_index(op.f('ix_exercise_logs_user_id'), table_name='exercise_logs')
    op.drop_index(op.f('ix_exercise_logs_session_id'), table_name='exercise_logs')
    op.drop_index(op.f('ix_exercise_logs_log_date'), table_name='exercise_logs')
    op.drop_index(op.f('ix_exercise_logs_langfuse_trace_id'), table_name='exercise_logs')
    op.drop_table('exercise_logs')
    op.drop_index(op.f('ix_conversation_messages_user_id'), table_name='conversation_messages')
    op.drop_index(op.f('ix_conversation_messages_session_id'), table_name='conversation_messages')
    op.drop_index(op.f('ix_conversation_messages_langfuse_trace_id'), table_name='conversation_messages')
    op.drop_table('conversation_messages')
    op.drop_table('user_memory')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_reports_user_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_langfuse_trace_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_llm_monitoring_logs_user_id'), table_name='llm_monitoring_logs')
    op.drop_index(op.f('ix_llm_monitoring_logs_langfuse_trace_id'), table_name='llm_monitoring_logs')
    op.drop_table('llm_monitoring_logs')
    op.drop_index(op.f('ix_daily_summaries_user_id'), table_name='daily_summaries')
    op.drop_table('daily_summaries')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
